/* Generated by Cython 3.2.5 */

#ifndef __PYX_HAVE__fernet
#define __PYX_HAVE__fernet

#include "Python.h"

#ifndef __PYX_HAVE_API__fernet

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *gen_safe_key(char const *);
__PYX_EXTERN_C PyObject *encrypt_string(char *, char *);
__PYX_EXTERN_C PyObject *decrypt_string(char *, char *);

#endif /* !__PYX_HAVE_API__fernet */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("fernet", PyInit_fernet) instead of calling PyInit_fernet directly from Python 3.5 */
PyMODINIT_FUNC PyInit_fernet(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"fernet\", PyInit_fernet) instead of calling PyInit_fernet directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"fernet\", PyInit_fernet) instead of calling PyInit_fernet directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"fernet\", PyInit_fernet) instead of calling PyInit_fernet directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_fernet_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_fernet() __PYX_WARN_IF_PyInit_fernet_INIT_CALLED(PyInit_fernet())
#endif

#endif /* !__PYX_HAVE__fernet */
