#!/bin/bash
function git_push ()
{
	git add .
	git commit -m "auto_commit_$(date)"
	git push
} 

git_push
gcc main.c -o /tmp/0bchat -lcrypto -g 
echo "---------------------------------------"
/tmp/0bchat $@
