#!/bin/bash
function git_push ()
{
	git add .
	git commit -m "auto_commit_$(date)"
	git push
} 

git_push
gcc main.c remote/cjson/cJSON.c remote/plib/plib.c remote/plib/lib/input.c -o /tmp/0bchat -g
echo "---------------------------------------"
/tmp/0bchat $@
