#!/bin/sh

ADDR="http://localhost"
PROG="$0"
PORT="$1"
METHOD="$2"
GID="$3"
MSG="$4"

# Handle METHOD and GID validity
if [[ ! -n "$METHOD" ||  ! -n "$GID" || (  ! "$METHOD" = "POST" &&  ! "$METHOD" = "GET") ]]; then
	echo "$PROG <PORT> <GET|POST> <GID>"
	exit 1;
fi

# Handle METHOD
case "$METHOD" in
	"GET")
		URI="$ADDR:$PORT/get/$GID"
		echo "-> $URI"
		curl "$URI"
		echo ""

		[ $? -eq 0 ] &&
			exit 0
	;;

	"POST")
		if [ ! -n "$MSG" ]; then
			echo "$PROG $PORT POST <GID> <MSG>"
			exit 1;
		fi

		URI="$ADDR:$PORT/post/$GID/$MSG"
		echo "-> $URI"
		curl "$URI"
		echo ""

		[ $? -eq 0 ] &&
			exit 0
	;;
esac
